<?php
/**
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper = $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $this->getSearchUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
        <div id="elasticsearch-indicator" style="display: none;position: absolute;top: 20px;left: 41px;">
            Working...
        </div>
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
            //<![CDATA[
            var magestore = new Elasticsearch.Magento('<?php echo $this->getBaseUrl() ?>');
            var elasticsearch = new Elasticsearch.Search('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>', magestore);
            elasticsearch.initAutocomplete('<?php echo $this->getSuggestUrl() ?>', 'search_autocomplete');
            //]]>
        </script>
    </div>
</form>